name: CI Practice

on:
  push:
    branches: [ master ]

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository files
        run: ls

      - name: Check README exists
        run: test -f DOES_NOT_EXIST.txt